server.port=8080
spring.application.name=WeatherBI

# Definições de log
logging.level.org.hibernate.SQL=off
logging.level.root=INFO
logging.file.name=/apps/weather_api/logs/log_weather_api.log
logging.pattern.console=%date|%clr(%-5level)|%thread|%clr(%-40.40logger{60}.%M:%L){cyan}|%msg%n%rootException
logging.pattern.file=%date|%clr(%-5level)|%thread|%mdc{login}|%mdc{session_id}|%mdc{server_ip}|%mdc{user_ip}|%logger{60}.%M:%L|%msg%n%rootException

# Banco de Dados SQL Server
spring.datasource.driver-class=name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WEATHER_BI
spring.datasource.username=sa
spring.datasource.password=

# Banco de Dados NoSQL (MongoDB)

# Liga/desliga Flyway multitenant
flywayMigrate=true

# Flyway
spring.flyway.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.sql-migration-prefix=V
spring.flyway.repeatable-sql-migration-prefix=R
spring.flyway.sql-migration-separator=__
spring.flyway.sql-migration-suffixes=.sql
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

# Swagger
springdoc.documentation.swagger.v2.api.info.title = Weather BI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Weather API
weather.api.token=
weather.api.url.base=http://api.weatherapi.com/v1

# Shedlock (para uso em 2 ou mais nós)
# O lock só será liberado após "tempo-minimo" segundos
shedlock.tempo-minimo=5
# Tempo máximo em segundos do lock, a ser liberado salvo se extender o lock
shedlock.tempo-maximo=120
# Tempo antes do fim do lock para que a necessidade de extensão seja analizada e feita
shedlock.margem-seguranca=20
# Indica se a extensão do tempo do lock será feita caso a margem de segurança seja ultrapassada
shedlock.extende-execucao=true
# Tempo adicionado ao lock na extensão com a ultrapassagem da margem de segurança
shedlock.extende-por=60
# Indica se o portador do lock (lockedBy) será atualizado com o nome da instância em execução
# Nome da instância: spring.application.name
shedlock.atualiza-portador-lock=false
shedlock.extende-portador-lock=false
# Habilita o uso do shedlock
shedlock.ativo=false