@startuml
'https://plantuml.com/class-diagram

class Country {
    id : BigInteger
    name : String
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

class FederalState {
    id : BigInteger
    name : String
    country : Country
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

class City {
    id : BigInteger
    name : String
    state : FederalState
    latitude : Decimal
    lontigute : Decimal
    averageAltitude : Decimal
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

class Neighborhood {
    id : BigInteger
    name : String
    city : City
    latitude : Decimal
    longitude : Decimal
    altitude : Decimal
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

class MeasurementLocation {
    id : BigInteger
    address : String
    neighborhood : Neighborhood
    city : City
    latitude : Decimal
    longitude : Decimal
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

class WeatherSource {
    id : BigInteger
    name : String
    apiBase : String
    active : boolean
    createdAt : LocalDateTime
    updatedAt : LocalDateTime
}

enum CollectionFrequency {
    MINUTE
    10_MINUTE
    HOUR
    HALF_DAY
    DAILY
}

class RealTimeData {
    id : BigInteger
    location : MeasurementLocation
    city : City
    latitude : Decimal
    longitude : Decimal
    collectedAt : LocalDateTime
    frequency : CollectionFrequency
    source : WeatherSource
}

class 10MinData {
    id : BigInteger
    location : MeasurementLocation
    city : City
    collectedAt : LocalDateTime
    fromResume : boolean
}

class HourlyData {
    id : BigInteger
    location : MeasurementLocation
    city : City
    collectedAt : LocalDateTime
    fromResume : boolean
}

class DailyWeatherData {
    id : BigInteger
    location : MeasurementLocation
    city : City
    collectionDate : LocalDate
    fromResume : boolean
}

Country "1" *-- "0..*" FederalState : contains >
FederalState "1" *-- "0..*" City : contains >

@enduml